import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/header/Navbar";
import localFont from "next/font/local";

import Scroll from "./components/scroll/Scroll";
import TopBar from "./components/topBar/TopBar";

const vazir = localFont({
  src: [
    { path: "../public/vazir-font-v16.1.0/Vazir-Thin.woff2", weight: "100" },
    { path: "../public/vazir-font-v16.1.0/Vazir-Light.woff2", weight: "300" },
    { path: "../public/vazir-font-v16.1.0/Vazir.woff2", weight: "400" },
    { path: "../public/vazir-font-v16.1.0/Vazir-Medium.woff2", weight: "500" },
    { path: "../public/vazir-font-v16.1.0/Vazir-Bold.woff2", weight: "700" },
  ],
  variable: "--font-vazir",
  display: "swap",
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="fa"
      dir="rtl"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased ${vazir.variable}`}
    >
      <body
        className="min-h-full flex flex-col"
        style={{ fontFamily: "var(--font-vazir)" }}
      >
        <TopBar />
        <Navbar />
        {children}
        <Scroll />
      </body>
    </html>
  );
}
